name: x86_64 CI
on:
  pull_request:
    branches:
      - '**'
      - '!mainline'

jobs:
  kernel-build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools and Libraries
        run: |
          sudo apt update
          sudo apt install -y build-essential libssl-dev ccache bison flex libelf-dev bc cpio
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build the Kernel
        run: |
          cp configs/kernel-x86_64-redfs-ci.config .config
          make olddefconfig
          make -j $(nproc)
